#!/bin/bash
curl -X POST -H 'Content-Type: application/json' http://localhost:8888/.netlify/functions/get_text_openAI \
--data '{"email": "abc@dddd.com", "query":"Was Plato more prolific than Socrates?"}'